using Microsoft.Extensions.Configuration;
using NYC360.Application.Contracts.Emails;
using NYC360.Application.Models.Emails;

namespace NYC360.Infrastructure.Email.Templates;

public sealed class AdminTicketNotificationTemplate(IConfiguration config) : IEmailTemplate<AdminTicketNotificationModel>
{
    public string Subject => "NYC360 - New Internal Support Ticket Alert";

    public string GenerateBody(AdminTicketNotificationModel model)
    {
        // Determine a highlight color based on priority
        //string color = model.Priority.Equals("Urgent", StringComparison.OrdinalIgnoreCase) ? "#e74c3c" : "#3498db";

        return $@"
        <div style=""font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; border: 1px solid #eee;"">
            <div style=""background-color: #e74c3c; color: white; padding: 20px; text-align: center;"">
                
            </div>
            <div style=""padding: 20px; color: #333;"">
                <p><strong>User:</strong> {model.UserFullName}</p>
                <p><strong>User Email:</strong> <a href=""mailto:{model.UserEmail}"">{model.UserEmail}</a></p>
                <p><strong>Subject:</strong> {model.Subject}</p>
                <hr style=""border: 0; border-top: 1px solid #eee; margin: 20px 0;"" />
                <p><strong>Message:</strong></p>
                <div style=""background-color: #f9f9f9; padding: 15px; border-left: 4px solid #e74c3c; italic;"">
                    {model.Message}
                </div>
            </div>
            <div style=""background-color: #f4f4f4; padding: 15px; text-align: center; font-size: 12px; color: #777;"">
                This notification was generated by the NYC360 Support System.
            </div>
        </div>";
    }
}